site_name: UnityNeuroSpeech Docs
site_url: https://hardcodedev777.github.io/UnityNeuroSpeech
theme:
  name: material
  logo: media/logo.png
  favicon: media/favicon.png
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest
    - header.autohide
nav:
  - Quickstart: index.md
  - Unity:
      - Steps to make it work: unity/steps-to-make-it-work.md
      - Agent API: unity/agent-api.md
      - Useful Tools: unity/useful-tools.md
repo_url: https://github.com/HardCodeDev777/UnityNeuroSpeech
copyright: Copyright &copy; 2025 HardCodeDev
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HardCodeDev777/UnityNeuroSpeech
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite